# Generated by Django 5.2.1 on 2025-05-28 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('semestre', models.CharField(max_length=10)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
            ],
        ),
    ]
