# Generated by Django 5.2.1 on 2025-06-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('grado_academico', models.CharField(choices=[('LIC', 'Licenciatura'), ('MAE', 'Maestría'), ('DOC', 'Doctorado'), ('POS', 'Posdoctorado')], default='LIC', max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
