# Generated by Django 5.2.1 on 2025-06-04 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('comision', 'comision'), ('admin', 'admin'), ('profesor', 'profesor'), ('alumno', 'alumno')], max_length=50, unique=True)),
                ('permisos', models.JSONField()),
            ],
        ),
    ]
