# Generated by Django 5.0.6 on 2025-05-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('comision', 'comision'), ('admin', 'admin'), ('profesor', 'profesor'), ('alumno', 'alumno')], max_length=50, unique=True),
        ),
    ]
