# Generated by Django 5.0.6 on 2025-05-29 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPreguntas',
            fields=[
                ('id_modulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaModulo',
            fields=[
                ('id_pregunta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=1000)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.modulopreguntas')),
            ],
        ),
    ]
