# Generated by Django 5.2.1 on 2025-06-04 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.estudiante'),
        ),
        migrations.AddField(
            model_name='preguntamodulo',
            name='id_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.modulopreguntas'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.criterio'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.evaluacion'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('estudiante', 'curso')},
        ),
    ]
