# Generated by Django 5.0.6 on 2025-06-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_modulopreguntas_preguntamodulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='criterio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.criterio'),
        ),
    ]
