# Generated by Django 5.0.6 on 2025-06-03 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('evaluacion', '0003_alter_respuesta_criterio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='criterio',
            name='nombre',
        ),
        migrations.AddField(
            model_name='criterio',
            name='calificacion',
            field=models.IntegerField(choices=[('1', 'Muy Deficiente'), ('2', 'Deficiente'), ('3', 'Regular'), ('4', 'Bueno'), ('5', 'Excelente')], default='1'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='id_criterio',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.criterio'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.docente'),
        ),
    ]
