# Generated by Django 5.0.6 on 2025-06-03 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_remove_criterio_descripcion_remove_criterio_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='id',
        ),
        migrations.AlterField(
            model_name='criterio',
            name='id_criterio',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
