# Generated by Django 5.0.6 on 2025-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_remove_criterio_id_alter_criterio_id_criterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='numero',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
