# Generated by Django 5.0.6 on 2025-06-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_criterio_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='numero',
        ),
    ]
