# Generated by Django 5.0.6 on 2025-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_remove_criterio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 'Muy Deficiente'), (2, 'Deficiente'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], default=1),
        ),
    ]
