# Generated by Django 5.0.6 on 2025-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_alter_criterio_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='criterio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='criterio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Criterio',
        ),
    ]
