# Generated by Django 5.0.6 on 2025-06-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_alter_evaluacion_criterio_alter_respuesta_criterio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='criterio',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.preguntamodulo'),
        ),
    ]
