# Generated by Django 5.0.6 on 2025-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_remove_evaluacion_criterio_respuesta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='comentario_general',
            field=models.TextField(blank=True, help_text='Comentario general sobre la evaluación', null=True),
        ),
    ]
