# Generated by Django 5.0.6 on 2025-06-11 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0012_remove_respuesta_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del periodo de evaluación', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del periodo de evaluación', null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del periodo de evaluación')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del periodo de evaluación')),
                ('fecha_comision', models.DateField(help_text='Fecha de reunión de comisión para revisión')),
                ('fecha_cierre', models.DateField(help_text='Fecha de cierre definitivo y publicación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de inicio'), ('activo', 'Activo'), ('revision', 'En revisión por comisión'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
